Repository PrestaShop/welcome, pull requests merged in 2020-12, with the labels that each got.

#93 Do not override the link smarty variable
  .github/workflows/php.yml
  OnBoarding/OnBoarding.php
  views/content.tpl
  welcome.php
Labels: QA ✔️, bug

#94 Bump version to 6.0.4
  config.xml
  welcome.php
Labels: enhancement

#95 Release 6.0.4
  .github/workflows/php.yml
  OnBoarding/OnBoarding.php
  README.md
  composer.lock
  config.xml
  logo.png
  package-lock.json
  package.json
  views/content.tpl
  welcome.php
Labels: QA ✔️, enhancement
