Repository PrestaShop/welcome, pull requests merged in 2020-10, with the labels that each got.

#76 Improve project
  .eslintignore
  .eslintrc.js
  .github/workflows/build-release.yml
  .github/workflows/js.yml
  .github/workflows/php.yml
  .gitignore
  .php_cs.dist
  OnBoarding/Configuration.php
  OnBoarding/OnBoarding.php
  OnBoarding/index.php
  composer.json
  composer.lock
  controllers/admin/AdminWelcomeController.php
  controllers/admin/index.php
  controllers/index.php
  images/index.php
  js/index.php
  js/module.js
  js/src/OnBoarding.js
  js/src/index.php
  package-lock.json
  package.json
  public/5452c6f6a92bc810c6e73210adfece55.png
  public/5e07cbde941cc1e24cbabe1c9a6c995a.png
  public/a216149cc722f1e24b5d3d266d623a09.png
  public/bc6b8d0cfbf337b153ae599072112b00.png
  public/c02d68433654ed03d38fdc6c2ae90112.png
  public/ca2f8d1c0c7a6830ef94b57264bc3b72.png
  public/eab7a4b5ee7f355e82c35a25542bb73d.png
  public/ec967aeab4fe4dbcbffd8097dda2d17c.png
  public/module.css
  public/module.js
  scss/index.php
  tests/index.php
  tests/phpstan/index.php
  tests/phpstan/phpstan.neon
  views/contents/index.php
  views/index.php
  views/templates/index.php
  webpack.config.js
  welcome.php
Labels: QA ✔️, enhancement

#67 Do not load onBoarding template if header is not displayed
  welcome.php
Labels: QA ✔️, bug

#87 Fix wrong conditions on steps
  config.xml
  js/src/OnBoarding.js
  public/module.css
  public/module.js
  scss/_navbar.scss
  welcome.php
Labels: QA ✔️

#88 Release 6.0.3
  config.xml
  js/src/OnBoarding.js
  public/module.css
  public/module.js
  scss/_navbar.scss
  welcome.php
Labels: enhancement
