Repository PrestaShop/welcome, pull requests merged in 2021-06, with the labels that each got.

#59 Uninstall module used on PS 1.6 before using this one
  welcome.php
Labels: QA ✔️

#116 Fix step1 of step 3/6 not showing in 1.7.8.x
  OnBoarding/Configuration.php
Labels: bug, waiting for QA

#114 Release 6.0.5
  .github/release-drafter.yml
  .github/workflows/php.yml
  OnBoarding/Configuration.php
  composer.lock
  config.xml
  controllers/admin/AdminWelcomeController.php
  js/module.js
  js/src/OnBoarding.js
  package-lock.json
  package.json
  public/module.js
  welcome.php
Labels: QA ✔️

#117 Wording correction
  README.md
  config.xml
  welcome.php
Labels: enhancement

#113 Update bourbon and adapts BCs
  package-lock.json
  package.json
  public/module.css
  scss/_advancement.scss
  scss/_navbar.scss
  scss/_popup.scss
  scss/_settings.scss
  scss/_tooltip.scss
  scss/module.scss
Labels: QA ✔️

#119 Release 6.0.6
  README.md
  composer.lock
  config.xml
  package-lock.json
  package.json
  public/module.css
  scss/_advancement.scss
  scss/_navbar.scss
  scss/_popup.scss
  scss/_settings.scss
  scss/_tooltip.scss
  scss/module.scss
  welcome.php
Labels: QA ✔️
